### ISSUE TITLE
Python Versioning Issues? Empty Control Net in 3.6.x, ValueErrors in 3.7.x

### ISSUE THREAD

**Issue by astrostu** [USGS-Astrogeology/plio#108]
I've re-installed Anaconda and ISIS3 and PLIO from scratch a few times over the last several hours trying to track this down and finally think I've at least figured out enough to identify the problem(s).  (Please note, I'm very new to Anaconda.)

I'm on macOS, and I installed Anaconda for Python 3.7.x.  It installs.  I then follow the instructions for installing an ISIS3 environment, with conda create -n isis3 python=3.6.  Activate that environment.  Install ISIS3.  Install PLIO.  Bring up a Python line (just type in "python") and then follow the PLIO example to import various packages, and then read in my control network with df = io_controlnetwork.from_isis("test.net").  It is done instantly, then I type "df" and it says "Empty IsisControlNetwork" and then lists the columns.  Note when doing this, it says the Python version is 3.6.7 (if I did not install PLIO, the version is 3.6.0 after the ISIS3 install, while if I start it using "python3" it's v. 3.6.8).

In contrast, if in the above paragraph I do NOT activate the isis3 environment but stick with base, install PLIO, bring up Python, and do the exact same thing, it takes several seconds and then when I type "df" I get a lovely listing of all the measures in my network that I can then manipulate.  I create a dictionary of all the serial numbers in the network.  But then when I try to write it out ("io_controlnetwork.to_isis('test_out.net', df, serials)"), I get errors on column names.  So I rename "id" to "point_id" and "type" to "point_type".  Try writing out again, and this time I get a "ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()." problem.  Note that when I do this, it says the Python version is 3.7.3.

Not sure what's going on there, but there appears to be a couple issues with the above, and it is entirely possible it's my ignorance of Anaconda:  (1) There's a Python 3.6.x issue with PLIO where no control net is read in though the column names are created (yes, I did verify I'm in the correct directory).  (2) There's a general problem where two column names that are read in are the wrong names for writing out.  (3) In Python 3.7.x, there's some sort of issue with a "ValueError."  That said on this last one, I can follow the example for a 5-point Apollo network and not get that error.  However, I'm literally reading the network in, renaming those two columns to not get an error of wrong names, creating my serial numbers dictionary with no duplicates, and then writing the network out, and getting that error.  (4) Not mentioned above, but when doing things in the order in my second paragraph, PLIO after ISIS3, PLIO removes the ISIS3 scripts/ directory, so I can no longer access ISIS3 commands and had to again run "conda install -c usgs-astrogeology isis3".

Help would be appreciated, and hopefully at least one of those errors is not my fault?

**Comment by jessemapel** [comment]
Right now ISIS doesn't play nicely with other Anaconda packages, so I'm not too surprised install order matters when installing both together. The Control Network sounds like genuine errors, though. I'll take a quick look at this next week.

**Comment by astrostu** [comment]
Lots more experimentation.  I solved one thing, made a workaround for another, and discovered what I think are several more bugs.

Fixed: The "ValueError" is me not understanding how to create proper Pandas dataframes and Dictionaries.

Workaround:  Calling PLIO from ISIS3 conda environments can be done by invoking "conda run -n [PLIO environment] [Python script that uses PLIO]".  So I can now call, from a Python script running ISIS3, PLIO stuff.

Bug 1: The issue of an empty control net in Python 3.6 remains.

Bug Set 2: I think there are several issues with control net versions for I/O in PLIO.  If I read in a v5 network (the only version I use), three column names are incorrect and several columns have extraneous information.  I invite you to simply read a net in and then do something like this: >> for column in df.columns: print(column + "\t\t" + str(df.loc[4][column])) <<.  When I do that (to output the 5th measure, arbitrarily), for instance the "datetime" field ends up being "datetime    2019-05-17T18:53:55\ndatetime    2019-05-17T18:53:55" (it's duplicated and has the "datetime" column name in there, separate from me printing out the name of the column).  The three incorrect column names are the first ("id" should be "point_id"), second ("type" should be "point_type"), and I think 25th ("type" should be "measure_type").

Bug Set 3: Writing out a reduced control net (just a few of the columns from a full, JIGSAW'd control net, for just a few (11) measures) has revealed more issues.  It does not respect "referenceIndex," instead making the first measure the reference.  Any True/False field that has any text other than "True" gets treated as "True" -- such as "ignore" set to "False" will still have the measure's Ignore set to "True" ... I have to make the field "" to get it to be "False."  I got errors whenever trying to put in any of the first four apriori columns (I didn't try the others).  It did not respect measure type nor point type.  Then, I thought it might be a version issue, so then I explicitly set "version=5" when calling io_controlnetwork.to_isis(), and I got errors.  I had to modify line 287 of io_controlnetwork.py to be "point_spec = cnh5.ControlPointFileEntryV0005()" and then I at least got a network written out, but then CNETBIN2PVL couldn't read it ("**ERROR** Unable to write control net to PVL file. Invalid control point has no point ID value.").  Despite it having a point ID and at least being able to convert to PVL when using version=2.  If I added a prefix when calling .to_isis, like "blah", I got a different error when trying to run CNETBIN2PVL on the output network: "**I/O ERROR** Reading the control network [test_out.net] failed.\n**I/O ERROR** Failed to convert protobuf version 2 control point at index [1] into a ControlPoint.\n**PROGRAMMER ERROR** The SerialNumber is not unique. A measure with serial number [MRO/CTX/0848006063:221] already exists for ControlPoint [blahMC18_01_spacing1x_ptA00000015]."  (Again, none of those errors were there with v2.)

Maybe some of these bugs have the same solution, and it's tied to working out the kinks in writing v5 networks?  That's what I was hoping, that when I was trying to solve Bug Set 3 that just setting that version=5 would solve Set 3 and 2, but, it just made some more issues.  I've attached a sample network, SN list, and the simple Python script (that reads the SN list) that I've been trying to work from to just do what I had hoped would be a simple read in, write out.

[test.net.zip](https://github.com/USGS-Astrogeology/plio/files/3226620/test.net.zip)

**Comment by astrostu** [comment]
Looks like it only attached the network.  Here's the Python script and SN list as a ZIP.
[Archive.zip](https://github.com/USGS-Astrogeology/plio/files/3226641/Archive.zip)

**Comment by jlaura** [comment]
A few items:

1. Please, open new bugs as independent bug reports.
1. Thank you for reporting. We are not currently directly funded to make changes to this library. Therefore, PRs are solicited with fixes for these issues. We will seek to fit in fixes, but we primarily support this library in our off time (nights and weekends).

**Comment by astrostu** [comment]
Shall I edit/delete the non-followups and move to (a) different threads?

**Comment by jessemapel** [comment]
@astrostu leave this open, I've gone ahead and created new issues for your other 2 bugs. These may be related and may have a common solution, but because they are all different "symptoms" we prefer to keep them in separate issues. If a single change fixes all of this, it can be noted in the pull request.

**Comment by jessemapel** [comment]
For some resolution on this, the empty control network is because the support for V5 ISIS control network isn't out in the current 1.2 release. We haven't figured out a release schedule yet, we're expecting to make a few tweaks to the control network support in the coming weeks. Once that is done, we should put out 1.3

**Comment by jlaura** [comment]
@jessemapel I think that this can be closed? Now that we have V5 read support in place.
