### ISSUE TITLE
Control Network dataframe column names are incorrect

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/plio#110]
Split from #108 and @astrostu

>I think there are several issues with control net versions for I/O in PLIO. If I read in a v5 network (the only version I use), three column names are incorrect and several columns have extraneous information. I invite you to simply read a net in and then do something like this: >> for column in df.columns: print(column + "\t\t" + str(df.loc[4][column])) <<. When I do that (to output the 5th measure, arbitrarily), for instance the "datetime" field ends up being "datetime 2019-05-17T18:53:55\ndatetime 2019-05-17T18:53:55" (it's duplicated and has the "datetime" column name in there, separate from me printing out the name of the column). The three incorrect column names are the first ("id" should be "point_id"), second ("type" should be "point_type"), and I think 25th ("type" should be "measure_type").

**Comment by jessemapel** [comment]
This is because we use the names of values from the protobuf files. This results in both different names from what ISIS generally uses and also conflicts where the control point and control measure have columns with the exact same name (things like jigsaw rejected have the same name for measures and points).

**Comment by astrostu** [comment]
That's what also causes the duplicate things (like the datetime issue)?  At least this is sort of something that can be worked around by someone who's fairly naïve (me!).  My workaround for the column names:

`df = io_controlnetwork.from_isis("test.net")
df.rename(columns={'id':'point_id'}, inplace=True)
columns_renamed = []
counter = 0
for column in df.columns:
    if column == 'type':
        if counter == 0: columns_renamed.append('point_type')
        if counter == 1: columns_renamed.append('measure_type')
        counter += 1
    else:
        columns_renamed.append(column)
df.columns = columns_renamed`

The duplicate data in columns, I haven't slogged all the way through yet.

**Comment by jessemapel** [comment]
That workaround should do the trick. I'm working on a solution in the code itself. We generate the column names by taking all of the control point attributes and appending all of the control measure attributes. I'm renaming the duplicates before we append them so this isn't needed.

**Comment by astrostu** [comment]
Of course, code-side would be better!

**Comment by jessemapel** [comment]
I think the duplicate values are due to there being duplicates of the `datetime` field in the protobuf. For each measure, there is a `datetime` field for the measure and a `datetime` field for the point. They both have the same name, so they are getting appended to.
