### ISSUE TITLE
pvl header on cnet output incorrect

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/plio#125]
Control networks output have defaults of None if values are not available. However, cpp has Null types for empty values and this causes issues if you attempt to merge control networks from isis and plio.

**Comment by jlaura** [comment]
Can you post in the fields where this is presenting?

**Comment by ladoramkershner** [comment]
I apologize, could you clarify? The fields of the pvl label, or the portion of code I believe is responsible?

**Comment by jlaura** [comment]
Sorry yes. What does the current error look like? Which fields are being effected? The protobuf spec should be handling the type conversion (none->null), so knowing where this is occurring will help get a soln cooked.

**Comment by ladoramkershner** [comment]
Attempting to run an isis cnetmerge on demo.net (plio generated) and hand_ground.net (isis generated):
**_cnetmerge inputtype=cnets base=demo.net cnet2=hand_ground.net onet=demo_wgrnd.net networkid='demo_wgrnd' log=demo_wgrnd.log description='demowithground'_**

and I receive the error:
**_USER ERROR Input [] does not target the same target as other Control Network(s)._**

looking at the labels of each of the cnets, demo.net has 
**_Group = ControlNetworkInfo
    NetworkId = None
    TargetName = None
    UserName = None
    Created = "2019-06-25 19:13:25"
    LastModified = "2019-06-25 19:13:25"
    Description = None
    NumberOfPoints = 263
    NumberOfMeasures = 1359
    Version = 2
  End_Group_**

and hand_ground.net has
**_Group = ControlNetworkInfo
    NetworkId        = Null
    TargetName       = Null
    UserName         = Null
    Created          = 2019-06-24T12:12:40
    LastModified     = 2019-06-24T12:12:40
    Description      = Null
    NumberOfPoints   = 4
    NumberOfMeasures = 30
    Version          = 5
  End_Group_**

**Comment by ladoramkershner** [comment]
Let me know if that is what you were looking for or if you would like more info!

**Comment by jlaura** [comment]
That is perfect! Shouldn't these both be target Mars? I thought ISIS didn't support an empty target to begin with? (so plio should error if no target). @jessemapel

**Comment by jessemapel** [comment]
I'm not sure what ISIS does with no target. I'd have to go look at the ISIS control net versioner.

**Comment by ladoramkershner** [comment]
They should, so that is another error. I am doing some hand stuff to get the cnets merged, but it should also be fixed. I will create a ticket

**Comment by jlaura** [comment]
Is this then a 'code working as expected' and we should make the change in AutoCNet (and improve the documentation/warning in here)?

**Comment by ladoramkershner** [comment]
I believe so, I will make a separate ticket here to clean it up/summarize.
