### ISSUE TITLE
Read in control networks do not have the same line/sample values

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/plio#133]
This code
```
from plio.io import io_controlnetwork as cnet

path = '/scratch/ladoramkershner/hand_reg/demo1_initialSR.net'
data = cnet.from_isis(path)
data_to_update = data[['id', 'serialnumber', 'apriorisample', 'aprioriline', 'sample', 'line']]
data_to_update['id'] = data_to_update['id'].apply(lambda row : int(row))
print(data_to_update)
```
produces (just using the first few as an example, but this is repeated throughout):
```
id            serialnumber  apriorisample   aprioriline       sample       line  
1  MRO/CTX/1154845662:221    1972.496294   1364.388076  1972.496294       1364.388076
1  MRO/CTX/0890918049:155    1726.831417  24263.652846  1719.927671       24277.195542
2  MRO/CTX/0890918049:155    2464.173072  24259.782704  2454.851663     24272.262202
```

However, if you look at the cnetbin2pvl the values read
```
Group = ControlMeasure
      SerialNumber  = MRO/CTX/1154845662:221
      Sample        = 1972.9962941563
      Line          = 1364.8880759266
      AprioriSample = 1972.4962941563
      AprioriLine   = 1364.3880759266
      Reference     = True

Group = ControlMeasure
      SerialNumber  = MRO/CTX/0890918049:155
      Sample        = 1720.4276711104
      Line          = 24277.695541632
      AprioriSample = 1726.8314169444
      AprioriLine   = 24263.652846352

Group = ControlMeasure
      SerialNumber  = MRO/CTX/0890918049:155
      Sample        = 2455.3516628311
      Line          = 24272.762201549
      AprioriSample = 2464.173072262
      AprioriLine   = 24259.782704382
    End_Group
```

The apriori line/sample are fine, but the line and sample values are off. It seems in the first two examples, it is just the tenths place is off. However, looking at the third example it is also off in the ones place. Additionally, the significant digits past the tenths place are correct.

NOTE: This control network was originally created using autocnet to_isis() and then the measures were subpixel registered by hand.

**Comment by jlaura** [comment]
This looks like `plio` is doing what it should be doing for the line/sample. The plio pixel origin is the upper left corner (0,0) for every pixel. The ISIS pixel origin is the center of the pixel (0.5, 0.5).

Here is where the write is adding the offset: https://github.com/USGS-Astrogeology/plio/blob/master/plio/io/io_controlnetwork.py#L289

Here is where the read is backing the offset out: https://github.com/USGS-Astrogeology/plio/blob/master/plio/io/io_controlnetwork.py#L209

The apriori-sample/-line look like they are not being handled correctly because those are coming in without the conversion from the ISIS standard to the `plio` standard, so the above lines (links) are going to need to also shift the apriori-line/-sample as well.

**Comment by ladoramkershner** [comment]
Well, my issue is that our database is using isis camera models and the control network on my computer is also in isis, so shouldn't the numbers be the same?

**Comment by jlaura** [comment]
So, this is an example of where autocnet needs to be doing the right thing and doing the addition/subtraction when the isis sensor is being used.

**Comment by ladoramkershner** [comment]
Except this conversion doesn't need to be happening at all. I think plio makes a blanket assumption that everything we hand it is in something other than isis pixel space (is that correct?).

If so, is there a way for us to communicate that the pixels do not need to be shifted?

**Comment by jlaura** [comment]
Why doesn't the conversion need to occur? Autocnet's matcher is removing the offset when the isis sensor is used. Is this being missed someplace else?

**Comment by ladoramkershner** [comment]
I am not sure where autocnet is removing this offset. iterative_phase()?

**Comment by jlaura** [comment]
https://github.com/USGS-Astrogeology/autocnet/blob/d8a1c2088f81434ab13892e4932f51514c17dc1b/autocnet/spatial/isis.py#L53
and
https://github.com/USGS-Astrogeology/autocnet/blob/d8a1c2088f81434ab13892e4932f51514c17dc1b/autocnet/spatial/isis.py#L72

**Comment by ladoramkershner** [comment]
It looks like it is getting a half pixel added based on if the source is image. However, our points are from an image, but were projected using the isis cam_type. So it is shifting everything a half pixel unnecessarily, I think. I think this code was written before the option for using isis cam vs csm cam was available.

I am not very familiar with how this piece of code ties in with everything else though, so I may be talking nonsense. However, do you think there is value in looking this portion of code over?

**Comment by jessemapel** [comment]
@ladoramkershner @jlaura It looks like PLIO is behaving as expected here and this is an autocnet issue. Can this be closed?

**Comment by ladoramkershner** [comment]
Yes, we were keeping it open for the conversation but we actually just reviewed autocnet for this and got it all sorted
