### ISSUE TITLE
socetnet2isis and isisnet2socet Applying Uneccessary 0.5 pixel shifts

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/plio#135]
As of #127 , plio has adopted a (0,0) pixel origin. Currently, the `socetnet2isis` and `isisnet2socet` bin scripts perform both an origin shift and a pixel origin correction. Based on the changes made to `to_isis()` and `from_isis()` in #127, the pixel origin correction in the bin scripts is now in error by 0.5 pixels in both the sample and line directions.

To fix this, the bin scripts should be changed to apply a pixel origin correction with a magnitude of 0.5 pixels, rather than 1.0 pixels. This should be as simple as modifying the following lines in the bin scripts:

https://github.com/USGS-Astrogeology/plio/blob/185a854774820cd0fc98c5621b4534fbf07f1d57/bin/socetnet2isis#L66-L67

https://github.com/USGS-Astrogeology/plio/blob/185a854774820cd0fc98c5621b4534fbf07f1d57/bin/isisnet2socet#L126-L127

**Comment by jessemapel** [comment]
@dpmayerUSGS Are you comfortable putting up a PR as you've already identified the fix?

**Comment by dpmayerUSGS** [comment]
@jessemapel That depends. What else would the PR need to contain other than edits to those 4 lines in order to be accepted and merged?

**Comment by jessemapel** [comment]
I'm fairly sure the scripts are not actually tested in the repo so that's it.

**Comment by dpmayerUSGS** [comment]
I can confirm that the scripts are not tested. I'll self-assign this issue.

**Comment by jessemapel** [comment]
Either @tthatcher95 or @acpaquette Can review as they originally worked on the scripts.
