### ISSUE TITLE
No module named pvl._collections

### ISSUE THREAD

**Issue by ryanbanderson** [USGS-Astrogeology/plio#152]
When I try to import libpyhat, I get an error related to plio:
![image](https://user-images.githubusercontent.com/3344800/93531722-8d9ff300-f8f4-11ea-8f5c-a08083f55091.png)

**Comment by jessemapel** [comment]
@ryanbanderson What version of PVL do you have installed? They recently release 1.0 and it changed some of the internal around.

**Comment by ryanbanderson** [comment]
Yeah, looks like that PVL release is the problem. If I downgrade PVL to 0.3.0 things work. I'll submit a fix to plio's import.
