### ISSUE TITLE
Update to PVL 1.0

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/plio#154]
The PVL library moved to 1.0 and changed some of its internals. Part of this work is #152, but we're seeing other issues such as:

```
    def create_pvl_header(self, version, headerstartbyte,
                      networkid, targetname, description, username,
                          buffer_header_size, points_bytes,
                          creation_date, modified_date):
        """
        Create the PVL header object
        Parameters
        ----------
        version : int
              The current ISIS version to write, defaults to 2
        headerstartbyte : int
                          The seek offset that the protocol buffer header starts at
        networkid : str
                    The name of the network
        targetname : str
                     The name of the target, e.g. Moon
        description : str
                      A description for the network.
        username : str
                   The name of the user / application that created the control network
        buffer_header_size : int
                             Total size of the header in bytes
        points_bytes : int
                       The total number of bytes all points require
        Returns
        -------
         : object
           An ISIS compliant PVL header object
        """
    
>       encoder = pvl.encoder.IsisCubeLabelEncoder
E       AttributeError: module 'pvl.encoder' has no attribute 'IsisCubeLabelEncoder'
plio/io/io_controlnetwork.py:464: AttributeError
```

**Comment by jlaura** [comment]
@AustinSanders @jessemapel I am having issues with plio and the PVL library was attempting to install as a dependency. I can see that pvl 1.0.1 was installed for the testing. It does not look like pvl 1.0.1 was used for the Conda build (that is then uploaded to anaconda). 

Once this release gets to Conda-forge, it looks like the build is still pulling pvl version 0.3.0. https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=214103&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

Am I interpreting these builds correctly?

**Comment by jessemapel** [comment]
Once we tag a release on PLIO, then we will move the conda-forge recipe to PVL >=1.0. This isn't released yet, though, so you will see PVL 0.3.0 on the current conda-forge build. If you're having issues with installing via conda-forge you should post an issue on the conda-forge feedstock.

**Comment by jlaura** [comment]
The USGS hosted plio has an identical problem. It looks like we only updated 1/2 of this project to PVL 1.0.1. The testing is using 1.0.1, the anaconda build and upload are not. This issue does not look closable because the update is not complete as far as I can tell from the build logs on this repository.

**Comment by jessemapel** [comment]
I am confused if you are having issues with the conda-forge build or the dev builds?

**Comment by jlaura** [comment]
Both are broken as far as I can tell. I think that the break in the repo is causing a down stream breakage hence the link to conda-forge builds.

**Comment by jessemapel** [comment]
@jlaura Can you post your environment config and the error message?

**Comment by jlaura** [comment]
To replicate:

```
conda create -n pliotest python=3.8
conda activate pliotest
mamba install -c usgs-astrogeology plio
```

The solver then solves to (snippet):
```
  plio               conda-forge/linux-64::plio-1.2.4-py38h32f6830_0
  poppler            conda-forge/linux-64::poppler-0.89.0-h4190859_1
  poppler-data       conda-forge/linux-64::poppler-data-0.4.9-0
  postgresql         conda-forge/linux-64::postgresql-12.3-h8573dbc_1
  proj               conda-forge/linux-64::proj-7.1.1-h966b41f_3
  protobuf           conda-forge/linux-64::protobuf-3.13.0.1-py38h950e882_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pvl                conda-forge/noarch::pvl-0.3.0-py_1
```

The plio build looks like the newest. The pvl build is version 0.3.0. 

In an interactive terminal:

```
>>> import plio
>>> plio.__version__
'1.2.4'
>>> import pvl
>>> pvl.__version__
'0.2.0'
>>>
```

Looking at the pvl version in the code base, I see:

```
__author__ = 'The PlanetaryPy Developers'
 __email__ = 'trevor@heytrevor.com'
__version__ = '0.2.0'
```

but conda is correct (I think) in listing 0.3.0 (via conda list).

**Comment by jessemapel** [comment]
@jlaura That is installing the conda-forge version which should use PVL 0.3.0 (I'm not sure why its version is just 0.2). It looks like the dev build we're pushing up is still labeled as 1.2.4 and the solver thinks that the conda-forge 1.2.3 build is better. Can you try `mamba install -c usgs-astrogeology plio=1.2.4=0_dev` to force it to install ours. When I do that, I get Pvl 1.0

**Comment by jessemapel** [comment]
We should change the version number for our dev builds to avoid this issue, but I'm not sure what it should be.
