### ISSUE TITLE
Administrative and Security Code Review

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/plio#170]
All software must have an administrative security review before it is made publicly available by any method. This type of review ensures personal, private, or otherwise sensitive information is not included in the repository. Types of sensitive information include:

 -  Personally identifiable information (PII)
 -  Absolute file system paths
 -  Internal server host names or IP addresses
 -  Usernames/passwords

Administrative security reviews may be performed by any trusted person; the reviewer does not necessarily need a strong scientific or programming background. When migrating an existing project into any non-private Git repository, it is important to remember that the entire project history needs to be reviewed if that history is to be maintained after migration.

**Comment by Kelvinrr** [comment]
From searching the I repo I have found: 

* No IP addresses
* No internal server hostnames 
* No usernames or passwords, closest thing to usernames are the usernames for control networks which are part of the control network spec. But these are more about tracking who made a control network and not about accessing some service. 
* No PII other than Jay's email in `setup.py` and the email in the license file `sqlalchemy_json/LICENSE` which I believe are OK. 
* A few absolute paths, some are ephemeral paths for miniconda as part of the appveyor.yml CI. But there are many in the SocetSet examples. 
  1. In the `.sup` files. These seem to be image file pointer but I do not see where these images are supposed to exist as they dont seem to be in the rep.  
  2. In `examples/SocetSet/CTX_Athabasca_Middle.prj`, assigned to the `DATA_PATH` variable which pointing to the directory for the `.sup` files. 

These paths are probably negligible, but if the line is absolutely no absolute paths we might have to remove these?

**Comment by jessemapel** [comment]
Ephemeral paths for CI are okay.

Any absolute paths for internal systems are not okay. So, we'll need to clean those out or make then relative paths.

**Comment by Kelvinrr** [comment]
Alright, found another in https://github.com/USGS-Astrogeology/plio/blob/master/plio/io/io_jsc.py, but all paths should be wiped from all history for all branches.
