### ISSUE TITLE
Mirror to code.usgs.gov

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/plio#174]

**Comment by Kelvinrr** [comment]
Pull mirroring isn't setup for code.usgs, so I think we are going to have to set up CI to simply push to code.usgs.gov whenever something is merged.

**Comment by Kelvinrr** [comment]
Forgot to add it to this repo, https://github.com/USGS-Astrogeology/plio/pull/175 should fix it.

**Comment by jlaura** [comment]
This is completed.
