### ISSUE TITLE
Add Citation for covariance calculation

### ISSUE THREAD

**Issue by ladoramkershner** [USGS-Astrogeology/plio#176]
Could we add a reference describing the calculation of the covariance?

https://github.com/USGS-Astrogeology/plio/blob/47af64c6f217210ad3409e58d8b0b5e7efd2e6fa/plio/utils/covariance.py#L4

**Comment by jessemapel** [comment]
What kind of reference are you looking for? The computation is standard error propagation $C_b = J_b(a) C_a J_b^T(a)$ and the jacobian is just the jacobian of the spherical to rectangular transform.

**Comment by ladoramkershner** [comment]
I agree with just upping the documentation, I don't think there needs to be a name change. I am also a bit worried about changing the return. Wouldn't that be considered API breaking?

**Comment by jessemapel** [comment]
That is a fuzzy part of API breaks. I would lean towards yes, and that likely makes it not worth it unless we have other breaks we want to do.

**Comment by ladoramkershner** [comment]
I am fine with just a documentation update! I will try throwing up a PR tomorrow
