### ISSUE TITLE
io_bae.py: Add read/write support for GXP-style GPFs

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/plio#24]
Socet GXP has added additional fields and header lines to ground point files (GPFs). We should add support for read/write of these new "GXP-style" GPFs while maintaining the ability to read/write the old style. 
Perhaps the easiest way to expose support to the user would be to add a keyword "format={GXP | Socet}?

**Comment by thareUSGS** [comment]
not sure the best way to handle an "isGXP_gpf" function. Perhaps.

`
def isGXP_gpf(input_data):
    """
    Read  first two lines to find out if Socet SET or Socet GXP gpf file

    Parameters
    ----------
    input_file : str
                 path to the input data file

    Returns
    -------
    boolean   : True, False
    """
    # If second line of the gpf is not an integer (or gpf count), then it is from GXP, else it is a Socet Set gpf 
    with open(input_data, 'r') as f:
        for i, l in enumerate(f):
            if i == 1:
                try:
                    cnt = int(l)
                    return False
                except ValueError:
                    return True
`

**Comment by thareUSGS** [comment]
not sure the best way to handle an "isGXP_gpf" function. Perhaps.

```
def isGXP_gpf(input_data):
    """
    Read first two lines to find out if Socet SET or Socet GXP gpf file

    Parameters
    ----------
    input_file : str
                 path to the input data file

    Returns
    -------
    boolean   : True, False
    """
    # If second line of the gpf is NOT an integer (or gpf count), then it is from GXP, 
    # else it is a Socet Set gpf 
    with open(input_data, 'r') as f:
        for i, l in enumerate(f):
            if i == 1:
                try:
                    cnt = int(l)
                    return False
                except ValueError:
                    return True

```

**Comment by dpmayerUSGS** [comment]
@thareUSGS The GXP-style GPFs appear to have introduced several new fields, but in the current example (https://github.com/USGS-Astrogeology/plio/blob/master/plio/examples/SocetGXP/GXP_example_gpf.gpf) those fields aren't populated; they don't even contain zeros or NaNs.

Do we have any examples of GXP-style GPFs where those fields are populated?
Because of the vagueness of how Socet Set/GXP describe their field labels, I'm not sure what the structure of the new "eigenpair" fields looks like. This in turn is making it difficult to update read_gpf() to support these files.

**Comment by jlaura** [comment]
@thareUSGS @dpmayerUSGS What is the status on this?

**Comment by jlaura** [comment]
Is this an issue with plio or something that needs to be moved over into the GXP repo where you all have a number of these research tasks?

**Comment by dpmayerUSGS** [comment]
This is a feature request or enhancement for 2 plio functions: `read_gpf()` and `save_gpf()`

It's a lower priority than it was when I initially opened it because subsequent research as part of the GXP project determined that GXP is backwards compatible with the Socet-style GPF format.

**Comment by jlaura** [comment]
I am going to close as I think(?) plio has full GXP read/write support. Let's reopen if not and we can get this issue updated with the current state.

**Comment by thareUSGS** [comment]
We can keep this closed but just to clarify for the future, "reading" in GXP was updated to support the newer GXP-style format for GPFs. But for writing nothing was changed. Thus the current GPF writer in PLIO maintains the original Socet SET-style GPF format. Fortunately, Socet GXP seems to support the Socet SET GPF-style format. 

Frankly, we are still not 100% what the new GXP parameters in the GPF are.

**Comment by jlaura** [comment]
@thareUSGS Thanks for the clarification. Maybe I'll update the issue name and specify just read. Then we can get a write issue open whenever appropriate.
