### ISSUE TITLE
Unable to install plio on MacOS: PackagesNotFoundError

### ISSUE THREAD

**Issue by astroindhu** [USGS-Astrogeology/plio#29]
When I run **`conda install -c usgs-astrogeology plio`** in a new conda environment created using command **`conda create --name usgs_plio python=3`**, I receive the following error message 

PackagesNotFoundError: The following packages are not available from current channels:

  - plio
  - pvl

Current channels:

  - https://conda.anaconda.org/usgs-astrogeology/osx-64
  - https://conda.anaconda.org/usgs-astrogeology/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch

Following are the speciations 
conda version: conda 4.5.0
python version: Python 3.6.5

Packages installated within usgs_plio conda environment 

# Name                    Version                   Build  Channel
ca-certificates           2018.03.07                    0
certifi                   2018.1.18                py36_0
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1                  hb4e282d_0
libffi                    3.2.1                h475c297_4
ncurses                   6.0                  hd04f020_2
openssl                   1.0.2o               h26aff7b_0
pip                       9.0.3                    py36_0
python                    3.6.5                hc167b69_0
readline                  7.0                  hc1231fa_4
setuptools                39.0.1                   py36_0
sqlite                    3.22.0               h3efe00b_0
tk                        8.6.7                h35a86e2_3
wheel                     0.31.0                   py36_0
xz                        5.2.3                h0278029_2
zlib                      1.2.11               hf3cbc9b_2

-- Awaiting solutions to fix my installation

**Comment by jlaura** [comment]
It looks like you are missing condo-forge in your channel listing.

PVL is available at: https://anaconda.org/conda-forge/pvl/files

See: https://conda.io/docs/user-guide/tasks/manage-channels.html for how to get the conda-forge channel added.

**Comment by astroindhu** [comment]
Ah - fixed it 👍 thanks a lot !!

**Comment by jlaura** [comment]
:+1:
