### ISSUE TITLE
socet2isis2socet close out

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/plio#41]
- [x] Fix the database MRO/Mars_Reconaissance_Orbiter issue
- [x] Get test data that we know is 'good'(@dpmayerUSGS)
- [ ] Check images that have > 2 measures - these look wrong in the example
- [x] Push current Jupyter notebook into `plio` and a single `bin` script (https://github.com/USGS-Astrogeology/plio/blob/master/bin/Socetnet2ISIS.py)
- [ ] Check with @dpmayerUSGS for socnet2isis.py arguments
- [x] Update setup.py to install bin script (@jlaura for help)
- [x] Go back the other way (no longer a stretch)
- [x] Add doc strings where appropriate (stretch goal in this sprint)
- [ ] Add examples into the doc string or write some tests (stretch goal in this sprint)

**Comment by jlaura** [comment]
@all see #38 for the two newly closed items

**Comment by tthatcher95** [comment]
@all - remaining now is cleanup on the tabular data - cneteditor is the program to use to make sure that the tabular data is converting correctly.

**Comment by jlaura** [comment]
@all this sprint has concluded.  Please open new issues as necessary for the socet2isis and isis2socet scripts.
