### ISSUE TITLE
plio on anacondacloud is out of date

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/plio#67]
As of this moment the version of plio available on https://anaconda.org/usgs-astrogeology/plio hasn’t been updated in over a month and it doesn’t reflect some important commits that have been made since then. 

Can someone please tick over the version number or do whatever else is necessary to trigger an update on conda?

**Comment by jlaura** [comment]
plio 0.1.4 is current as of 11 minutes ago.

https://anaconda.org/usgs-astrogeology/plio
