### ISSUE TITLE
Can't Generate ISIS3 serial numbers from IdealCamera

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/plio#86]
I'm trying to generate ISIS3 serial numbers from some cubes that contain noproj'd HiRISE image data. Thus, SpacecraftName and InstrumentId as reported in their labels are "IdealSpacecraft" and "IdealCamera," respectively. However, when I run `generate_serial_number()` I just get the warning message "Unable to load an appropriate image translation"

The cubes themselves are definitely valid and are the result of rather routine processing. Is there an error or a missing entry in `data.db` ?

Minimum steps to reproduce:
```
import plio.io.io_controlnetwork as cn
import plio.io.isis_serial_number as sn

sn.generate_serial_number('ESP_034830_2025_REDmos_hijitreged.balance.noproj.8bit.cub')
```
I've attached the label from one of the cubes.

[ESP_034830_2025_REDmos_hijitreged.balance.noproj.8bit.tar.gz](https://github.com/USGS-Astrogeology/plio/files/2527435/ESP_034830_2025_REDmos_hijitreged.balance.noproj.8bit.tar.gz)

**Comment by thareUSGS** [comment]
This line from the original may inform how to handle HiRISE here. If "Ideal" it actually goes to "OriginalInstrument" section. We may need to do the same in this code.
https://github.com/USGS-Astrogeology/socet_set/blob/cafaced396d6d7e5267abe422475d978e82b352e/SS4HiRISE/Tutorials/ISD_keyword_examples/socetlinescankeywords_forReferenceOnly.cpp#L114

**Comment by dpmayerUSGS** [comment]
That's interesting. plio is definitely not doing that, and neither is ISIS3's own `getsn`.

**Comment by dpmayerUSGS** [comment]
I'm going to close this because it appears that it's not actually a bug in plio. In fact, `generate_serial_number()` is behaving the same as ISIS3's own `getsn` when applied to an IdealCamera. 
The workaround that Trent cites above may not be appropriate for general use, and therefore may not be appropriate for plio.
