### ISSUE TITLE
remove TypeError from except

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/plio#89]
https://github.com/USGS-Astrogeology/plio/blob/f64c426c2c5266d4de1dcb5cf244e16ec3a2a9ce/plio/utils/utils.py#L50

This throws an error instead of just returning a string "s". I think just changing to expect: will fix it. e.g.:
frpm
    except TypeError:
to
    except:

**Comment by jlaura** [comment]
@thareUSGS I think that `TypeError` is the desired behavior. If the passed variable can be converted to float it is, but if the past variable is not convertible it is a error in type conversion.

I am going to close, but please reopen if you think a different error type is more descriptive.

Docs:
[https://docs.python.org/3.7/library/exceptions.html#TypeError](https://docs.python.org/3.7/library/exceptions.html#TypeError)
