### ISSUE TITLE
plio segfaults under Python 3.5

### ISSUE THREAD

**Issue by dpmayerUSGS** [USGS-Astrogeology/plio#93]
The latest build for plio under Python 3.5 for Linux installs with conda just fine (```conda install -c usgs-astrogeology plio python=3.5```), but invoking any of the bin scripts or attempting to import anything from the plio namespace within a Python script results in an immediate segmentation fault with no further messages.

Is this possibly due to an issue with GDAL?

**Comment by jlaura** [comment]
Going to close as we aren't building for 3.5 anymore. @dpmayerUSGS Please reopen if you see this happening in py3.6 or py3.7.
