### ISSUE TITLE
ChemCam Test Data Size too large

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/plio#94]
The ChemCam data is likely larger than it needs to be. Can the data be reduced while maintaining the efficacy of the tests?

**Comment by ryanbanderson** [comment]
I'll take a look at this and #95 when I get the chance. LIBS spectra tend to have thousands of wavelengths, so they end up large, but yes we can probably shrink the files if they're being used strictly for testing.

**Comment by jlaura** [comment]
I know that this issue is also quite old. I do not believe it is an issue any longer. I am going to close. Please reopen as needed.
